STRESS_GLOSSARY: dict[str, str] = {
    "METs": "Metabolic equivalents — a measure of exercise capacity. Higher is better. 10+ METs is excellent fitness.",
    "Bruce Protocol": "A standard treadmill test that increases speed and incline every 3 minutes.",
    "Modified Bruce": "A gentler version of the Bruce Protocol with easier starting stages.",
    "MPHR": "Maximum predicted heart rate, estimated as 220 minus your age.",
    "% MPHR": "The percentage of your maximum predicted heart rate reached during the test.",
    "Target Heart Rate": "The heart rate you should reach during exercise to make the test meaningful, usually 85% of your maximum predicted heart rate.",
    "Rate-Pressure Product": "Heart rate multiplied by systolic blood pressure — estimates how hard the heart is working.",
    "RPP": "Rate-pressure product — heart rate times systolic blood pressure. Reflects cardiac workload.",
    "ST Depression": "A change on the ECG tracing that can suggest reduced blood flow to the heart muscle during exercise.",
    "ST Elevation": "A change on the ECG tracing that can indicate significant coronary artery blockage.",
    "ST Segment": "A part of the heart's electrical tracing (ECG) that changes when the heart muscle is not getting enough blood.",
    "Ischemia": "Reduced blood flow to the heart muscle, often caused by narrowed coronary arteries.",
    "Duke Treadmill Score": "A scoring system that combines exercise time, ST changes, and symptoms to estimate heart disease risk.",
    "Chronotropic Incompetence": "The heart rate does not increase as much as expected during exercise, which may indicate a heart rhythm issue.",
    "Exercise Capacity": "How much physical work your body can perform, measured in METs or exercise duration.",
    "Recovery Phase": "The cool-down period after peak exercise, when heart rate and blood pressure return toward resting levels.",
    "Angina": "Chest pain or discomfort caused by reduced blood flow to the heart muscle.",
    "Dyspnea": "Shortness of breath.",
    "PVCs": "Premature ventricular contractions — extra heartbeats originating from the lower chambers of the heart.",
    "VT": "Ventricular tachycardia — a rapid heart rhythm from the lower chambers that may require treatment.",
    "SVT": "Supraventricular tachycardia — a rapid heart rhythm from the upper chambers of the heart.",
    "Arrhythmia": "An abnormal heart rhythm.",
    "Blood Pressure Response": "How your blood pressure changes during exercise. It normally rises with exercise and falls during recovery.",
    "Hypotensive Response": "An abnormal drop in blood pressure during exercise, which can be a sign of heart problems.",
    "Double Product": "Another name for rate-pressure product (heart rate times systolic blood pressure).",
    "Functional Capacity": "A measure of how well your cardiovascular system performs during physical activity.",
    "Positive Stress Test": "The test suggests possible reduced blood flow to the heart during exercise.",
    "Negative Stress Test": "The test did not show signs of reduced blood flow to the heart during exercise.",
    "Equivocal": "The test results are unclear and may need further evaluation.",
    "Non-diagnostic": "The test could not be fully interpreted, often because the target heart rate was not reached.",
    "Treadmill": "The exercise machine used for walking or running during the stress test.",
    "ECG": "Electrocardiogram — a recording of the heart's electrical activity.",
    "EKG": "Another abbreviation for electrocardiogram (from the German spelling).",
}
